services:
  PrestaShop\Module\DashGoals\Controller\ConfigurationController:
    public: true
    autowire: true
    autoconfigure: true

  PrestaShop\Module\DashGoals\Type\ConfigurationType:
    tags: ['form.type']
